GCC=g++
#GCC=/cvmfs/sft.cern.ch/lcg/releases/gcc/9.2.0/x86_64-centos7/bin/g++
#CXXFLAGS=`root-config --libs --cflags` -O3 -I/usr/include/boost/ -L/usr/lib64/ -lboost_program_options -I/home/users/bianchini/Eigen/eigen-3.4.0
CXXFLAGS=`root-config --libs --cflags` -lRooFit -lRooFitCore -lMinuit2 -O3 -I/usr/include/boost/ -L/usr/lib64/ -lboost_program_options -I/usr/include/eigen3

SRCDIR=.
BINDIR=.

.PHONY: all
all:
	$(info, "--- Full compilation --- ")	
	$(info, "-> if you want just to recompile something use 'make fast' ")	
	$(info, "------------------------ ")	
	$(MAKE) massscales 


massscales: massscales.cpp
	$(GCC) $(CXXFLAGS) -o $(BINDIR)/massscales massscales.cpp  
